---
apiVersion: v1
kind: Service
metadata:
  name: second-app
  namespace: production
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"

spec:
  ports:
    - name: http
      port: 8080
  selector:
    app: second-app
