apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: first-app-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: first-app
  namespaceSelector: 
    matchNames:
      - staging
      - backend
  endpoints:
  - port: http
    path: /metrics
    interval: 10s
    scrapeTimeout: 10s
    
