apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: First-app-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: First-app
  namespaceSelector: 
    matchNames:
      - staging
  endpoints:
  - port: http
    path: /metrics
    interval: 10s
    scrapeTimeout: 10s
    
